spring:
  config:
    name: titleAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/titles
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  #????? ??? ?????? ??????????? ?? ????????? ?? ???????? ?? update

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
server:
  port: 8081
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
